### ISSUE TITLE
Create a method of instantiation for single collection of issues for use in websites

### ISSUE THREAD

**Issue by XertroV** [secure-vote/sv-app#8]
We need ppl to be able to instantiate a smaller version of the sv-app in a website with the following method:

- Call Elm init function on a div, passing in a record of parameters
  - Users private key
  - Info on the specific subdemocracy to view (such as a `democID` or another reference - might need to hardcode some constants on our end)
  - Any other info (TODO)

This view should look and act like a normal view of a democracy

**Comment by TomSesselmann** [comment]
Can we close this ticket @XertroV ?
